blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/webmint/jira-clone/blob/main/README.md
    about: Check the project documentation
  - name: 💬 Discussions
    url: https://github.com/webmint/jira-clone/discussions
    about: Ask questions and discuss ideas